name: Custom automatic assignment grader
description: Grade assignment by providing oracle source code

inputs:
  question-id:
    description: Question ID that is passed as the first command line argument
    required: true
  stdin-file:
    description: Path to file containing newline-separated list of inputs that is fed to standard input
    required: true
  stdout-file:
    description: Path to file containing newline-separated list of expected values of standard output
    required: false
  time-limit:
    description: Maximum execution time allowed
    required: false
    default: 2s
  memory-limit:
    description: Maximum memory usage allowed
    required: false
    default: 256m

outputs:
  correct-cases:
    description: Number of correct outputs
    value: ${{ steps.}}
  total-cases:
    description: Number of all cases tested

runs:
  using: composite
  steps:
    - name: Format input and output file names
      id: path
      run: |
        echo "i=${{ inputs.stdin-file }}" >> $GITHUB_OUTPUT
        echo "p=${{ github.workspace }}/${{ hashFiles(inputs.stdin-file) }}-prophecy.txt" >> $GITHUB_OUTPUT
        echo "a=${{ github.workspace }}/${{ hashFiles(inputs.stdin-file) }}-attempt.txt" >> $GITHUB_OUTPUT
      shell: bash

    - name: Generate prophecy values from oracle code
      if: ${{ ! inputs.stdout-file }}
      run: |
        ./script/build.sh ${{ github.action_path }}
        ${{ github.action_path }}/build/assignment \
          ${{ inputs.question-id }} \
          $(wc -l <${{ steps.path.outputs.i }}) \
          <${{ steps.path.outputs.i }} \
          >${{ steps.path.outputs.p }}
        ./script/clean.sh ${{ github.action_path }}
      shell: bash

    - name: Copy prophecy file
      if: ${{ inputs.stdout-file }}
      run: cp ${{ inputs.stdout-file }} ${{ steps.path.outputs.p }}
      shell: bash

    - name: Build student image
      run: |
        docker build \
          --build-arg TIME_LIMIT=${{ inputs.time-limit }} \
          --tag attempt \
          ${{ github.workspace }}
      shell: bash
        
    - name: Run student container
      run: |
        docker run \
          --name "attempt-container" \
          --cap-drop ALL \
          --cpus 1.0 \
          --interactive \
          --memory ${{ inputs.memory-limit }} \
          --memory-swap ${{ inputs.memory-limit }} \
          --network none \
          --read-only \
          --security-opt no-new-privileges \
          attempt:latest \
          ${{ inputs.question-id }} \
          $(wc -l <${{ steps.path.outputs.i }}) \
          <${{ steps.path.outputs.i }} \
          >${{ steps.path.outputs.a }}
      shell: bash

    - name: Check student container status
      id: status
      run: |
        if docker inspect attempt-container >/dev/null 2>&1; then
          printf "out-of-memory=%s\n" $(docker inspect -f '{{ .State.OOMKilled }}' attempt-container) >> $GITHUB_OUTPUT
          printf "exit-code=%s\n" $(docker inspect -f '{{ .State.ExitCode }}' attempt-container) >> $GITHUB_OUTPUT
        fi
        docker rm -f attempt-container >/dev/null 2>&1 || true
      shell: bash

    - name: Print container status
      run: |
        echo "::notice::oom? ${{ steps.status.outputs.out-of-memory }}"
        echo "::notice::exitcode? ${{ steps.status.outputs.exit-code }}"
      shell: bash
