name: Automatically grade the submission

on:
  - push
  - repository_dispatch
  - workflow_dispatch

jobs:
  # TODO: run testcases in separate jobs

  apocalypse:
    runs-on: ubuntu-latest
    outputs:
      total-points: ${{ steps.grader.outputs.total-points }}
      max-points: ${{ steps.grader.outputs.max-points }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Grade with existing input/output
        id: grader
        uses: ./ # TODO: replace this with the grading action
        with:
          question-id: 1
          stdin-file: ./example/01-input.txt
          stdout-file: ./example/01-output.txt

  prophecy:
    runs-on: ubuntu-latest
    outputs:
      total-points: ${{ steps.grader.outputs.total-points }}
      max-points: ${{ steps.grader.outputs.max-points }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Grade with existing input and generated output
        id: grader
        uses: ./ # TODO: replace this with the grading action
        with:
          question-id: 1
          stdin-file: ./example/02-input.txt

  grade:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    needs: # TODO: add grader jobs as dependency
      - apocalypse
      - prophecy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Combine all grading results
        id: result
        run: |
          TOTAL_POINTS=$(( APOCALYPSE_TOTAL_POINTS + PROPHECY_TOTAL_POINTS ))
          MAX_POINTS=$(( APOCALYPSE_MAX_POINTS + PROPHECY_MAX_POINTS ))
          echo "total-points=$TOTAL_POINTS" >> $GITHUB_OUTPUT
          echo "max-points=$MAX_POINTS" >> $GITHUB_OUTPUT
        env:
          APOCALYPSE_TOTAL_POINTS: ${{ needs.apocalypse.outputs.total-points }}
          APOCALYPSE_MAX_POINTS: ${{ needs.apocalypse.outputs.max-points }}
          PROPHECY_TOTAL_POINTS: ${{ needs.prophecy.outputs.total-points }}
          PROPHECY_MAX_POINTS: ${{ needs.prophecy.outputs.max-points }}

      - name: Notify classroom
        uses: ./.github/actions/notify-classroom
        with:
          total-points: ${{ steps.result.outputs.total-points }}
          max-points: ${{ steps.result.outputs.max-points }}
