name: Test this action

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run automatic grader
        uses: ./
        with:
          question-id: 1
          stdin-file: ./example/01-input.txt
