name: Test this action

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Grade with existing input/output
        uses: ./
        with:
          question-id: 1
          stdin-file: ./example/01-input.txt
          stdout-file: ./example/01-output.txt

      - name: Grade with existing input and generated output
        uses: ./
        with:
          question-id: 1
          stdin-file: ./example/02-input.txt
